name = "proxy"
compatibility_date = "2024-01-01"

# Cloudflare Pages static assets - only include HTML/CSS/JS
[assets]
directory = "."
include = ["*.html", "*.css", "*.js", ".gitignore"]
exclude = ["node_modules", "package.json", "wrangler.toml"]
